database:
  host: 127.0.0.1
  user: root
  password:
  dbname: mvc
app:
  name: medevia
  description: todo
  author: Prin'Meshia
  version: 1.0.0
system:
  cache: false
  env: dev
path:
  root: /mvc
  public : /public

  
